version: '3.3'

services:

 mysql:
  container_name: mysql
  image: "mysql:latest"
  command: --default-authentication-plugin=mysql_native_password
  network_mode: "host"
  restart: always
  volumes:
   - "/home/iobroker/mysql:/var/lib/mysql"
   - "/etc/localtime:/etc/localtime:ro"
   - "/etc/timezone:/etc/timezone:ro"
  environment:
   MYSQL_ROOT_PASSWORD: ma5efhM6
   MYSQL_DATABASE: iobroker
   MYSQL_USER: iobroker
   MYSQL_PASSWORD: ma5efhM6

 ioBroker:
  container_name: iobroker
  image: "buanet/iobroker:latest"
  network_mode: "host"
  restart: always
  devices:
   - "/dev/ttyACM0:/dev/ttyACM0"
  volumes:
   - "/etc/localtime:/etc/localtime:ro"
   - "/etc/timezone:/etc/timezone:ro"
   - "/home/iobrokerdata:/opt/iobroker"
  environment:
   - TZ=Asia/Tashkent
   - LANG=en_US.UTF-8
   - LANGUAGE=en_US:en
   - LC_ALL=en_US.UTF-8
   - AVAHI=true
   - USBDEVICES="/dev/ttyACM0"
   - PACKAGES=nano
